export const SELECT_WEAPON = 'SELECT_WEAPON';
export const DESELECT_WEAPON = 'DESELECT_WEAPON';
export const SELECT_SHOE = 'SELECT_SHOE';
export const DESELECT_SHOE = 'DESELECT_SHOE';
export const SELECT_CLOTHING = "SELECT_CLOTHING";
export const DESELECT_CLOTHING = "DESELECT_CLOTHING"
export const DESELECT_ALL = 'DESELECT_ALL';
